export const products = [
    {
        id: 1,
        tipo: 'Ravioles',
        descripcion: 'deliciosas pastas con salsa filetto, ideales para acompañar con vino tinto',
        precio: 350,
        stock: 10,
        urlImg: 'https://res.cloudinary.com/diivxdasa/image/upload/v1617049814/ravioles_kiktkm.jpg',
    },
    {
        id: 2,
        tipo: 'Canelones',
        descripcion: 'abundante porcion de exquisitos canelones a la crema rellenos de verdura',
        precio: 450,
        stock: 8,
        urlImg: 'https://res.cloudinary.com/diivxdasa/image/upload/v1617049813/canelones_jq0yng.jpg',
    },
    {
        id: 3,
        tipo: 'Sorrentinos',
        descripcion: 'caseros y sabrosos sorrentinos con champignones acompañados con salsa de curry',
        precio: 500,
        stock: 12,
        urlImg: 'https://res.cloudinary.com/diivxdasa/image/upload/v1617049813/sorrentinos_bfkwmh.jpg',
    },
    {
        id: 4,
        tipo: 'Ravioles',
        descripcion: 'rellenos de verdura con una exquisita salsa parisienne, la estrella de la casa',
        precio: 350,
        stock: 15,
        urlImg: 'https://res.cloudinary.com/diivxdasa/image/upload/v1617223710/salsa-parisienne_fdkx21.jpg',
    },
    {
        id: 5,
        tipo: 'Canelones',
        descripcion: 'rellenos de ricota y nuez, acompañado de salsa bolognesa y queso rallado',
        precio: 450,
        stock: 16,
        urlImg: 'https://res.cloudinary.com/diivxdasa/image/upload/v1617223443/canelonesricota_i7uqdq.jpg',      
    },
    {
        id: 6,
        tipo: 'Sorrentinos',
        descripcion: 'deliciosos sorrentinos salteados con trozos de carne y salsa scarparo',
        precio: 500,
        stock: 5,
        urlImg: 'https://res.cloudinary.com/diivxdasa/image/upload/c_scale,h_190,w_286/v1617237291/sorrentinos-scarpa_brbhrt.jpg',      
    }
]